development:
 host: localhost:3000

production:
 host: localhost:3000

paths:
 sign_in: /users/sign_in.json
 create_plt: /presentation_layer_templates
 update_plt: /presentation_layer_templates
 delete_plt: /presentation_layer_templates
 get_plt: /presentation_layer_templates.json
 get_websites: /users/websites.json
 get_widgets: /widgets.json
 create_widget: /widgets.json
 update_widget: /widgets.json
 delete_widget: /widgets.json
 configure_widget: /widgets/configure.json
 delete_widget_device_template: /widgets/delete_device_template.json
 get_widget_device_templates: /widgets/device_templates.json
